library(dplyr)
library(magrittr)
library(lubridate)
library(bit64)
library(stringr)
Sys.setenv(HADOOP_CONF_DIR='/etc/hadoop/conf.cloudera.hdfs')
strCurrentUser<-Sys.info()[["user"]]
sysdate<-ceiling_date(as.POSIXct(Sys.Date(),tz = "EET"),unit = "month")-months(1)
strMonths<-substr(sysdate,1,7)
strLogName<-str_glue("logs-{strMonths}.log")
strOutputPath<-str_glue("~/.auditlogs/{strLogName}")
strHdpRMCMd<-str_glue("hdfs dfs -rm  /user/hive/warehouse/auditdb.db/audit_rserver/{strCurrentUser}/{strLogName}")
strHdpPutCmd<-str_glue("hdfs dfs -put {strOutputPath} /user/hive/warehouse/auditdb.db/audit_rserver/{strCurrentUser}")
lns <- readLines("~/.rstudio/history_database") %>% str_split(pattern=":",n=2)
hist_db <- data_frame(epoch=as.integer64(sapply(lns,"[[",1)),history=sapply(lns,"[[",2))

hist_db %<>% mutate(datetime = as.POSIXct(epoch/1000,origin = "1970-01-01",tz = "EET"))
hist_db %<>% mutate(date = ceiling_date(datetime,unit = "day")-days(1))
hist_db %<>% mutate(month=substr(date,1,7))
hist_db<-subset(hist_db,hist_db$month==strMonths)

write.table(hist_db,file=strOutputPath,sep = '\t',quote=FALSE,row.names=FALSE,col.names=FALSE)
system(strHdpRMCMd)
system(strHdpPutCmd)